### PR TITLE
add ExecReload to reload puma.

### PR DESCRIPTION
**Pull request by matyapiro31**
This enables puma to reload changes without restarting process.

### CODE REVIEW

**Comment by matyapiro31** [comment]
No, I mean hot restart in this document.
https://github.com/puma/puma/blob/master/docs/restart.md
However, default configuration of mastodon is cluster mode, so mastodon can use phased restart, too.
Phased restart is safer than hot restart and no down time.
Changed to SIGUSR1.

**Comment by nightpool** [comment]
This does nothing on mastodon, because it's preloaded

>Preloading can’t be used with phased restart, since phased restart kills and restarts workers one-by-one, and preload_app copies the code of master into the workers.

**Comment by nightpool** [comment]
(I was toying with implementing phased_restart a while ago but the memory difference in preload vs non-preload made it not worth it)

**Comment by matyapiro31** [comment]
@nightpool This is not for preloading.
This is safe restarting command for puma.Mastodon's upgrade is not applied until puma restarts, however restarting the process via `systemctl restart mastodon-web` takes some time.
This adds option to reload the change without downtime.Faster than killing process and relaunching puma server. Actually this command doesn't load puma's configuration, but it can reload mastodon's change.

**Comment by nightpool** [comment]
Again, this configuration *does not work* with current mastodon.

Mastodon uses preload_app. therefore, USR1 is identical to a full restart

**Pull request merged**
