### PR TITLE
Add instructions to make simple change to system - Rename "Toot!" button

### PR DESCRIPTION
**Pull request by awooga**
… code

A very simple quick change example to the code base - like "Hello World" - to prove your development can be altered. @agoni and @awooga olde developers (50+ ) made this :0

### CODE REVIEW

**Comment by matyapiro31** [comment]
This is no useless.

**Comment by awooga** [comment]
"This is no useless" is gramatically incorrect english - and thus means is not clear.

Do you mean "No" because "its useless" ? 

Hello world is useless to - but everyone writes it in every language ever written - first thing programmers/developers do - same with Mastodon - whats first thing you do when you have a system - make a simple change - and prove it works and you understand how to build new version ;)

**Comment by matyapiro31** [comment]
Please use .md for name, and those are not special things to be written here.

I think you may post your topic on somewhere.

**Comment by awooga** [comment]
Thanks for guidance, taken this on board. 
Would be nice to have simple instruction of simple quick change - that proves you can develop system.

**Comment by wxcafe** [comment]
This is not the place for something like this. Make a blog post or someting.

**Pull request closed without merging**
