### PR TITLE
Use fictitious domain in blocking example

### PR DESCRIPTION
**Pull request by Sjors**
Not sure how to test this locally.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by michaelfolkson** [comment]
Thanks for merging this @Gargron. Personally I didn't think it was a big deal but it will save this discussion from being repeated ad nauseam on the bitcoinhackers instance in future

**Comment by Sjors** [comment]
It seems I did something wrong. Maybe it doesn't like the Github markdown syntax?

**Comment by Sjors** [comment]
#825 contains instructions for testing on a local dev machine, in case anyone gets around to fixing the above before I do

**Comment by verretor** [comment]
> It seems I did something wrong. Maybe it doesn't like the Github markdown syntax?
> 
> 597E3FFB-3557-44B7-AE8E-C579A320928E

What happens if you remove ` | height=200`?

**Pull request merged**
