### PR TITLE
Anonymous git URL is easier for the initial git clone

### PR DESCRIPTION
**Pull request by alexte**
HTTPS hint added

### CODE REVIEW

**Comment by nightpool** [comment]
The second addition is written in a way that might be confusing to new admins. You talk about "SSH-ing in" to the server, but that's colloquially associated only with shell access—not port forwarding.

**Comment by alexte** [comment]
You are right it might be confusing, but I wanted to explain that you can use ssh for remote port forwarding to localhost:3000 onto the docker server

What would you write?

**Comment by nightpool** [comment]
Not sure if it's necessary—if you want to test that things are working, `curl` works just fine. If you want to browse your instance, you should set up nginx following the steps in the production guide.

**Comment by alexte** [comment]
OK feel free to use ether part. I think the changed git URL and the HTTPS part is still useful.

**Comment by nightpool** [comment]
Looks good, thanks! We can maybe fix up this section and incorporate the port-forwarding/localhost thing in a cleaner way—I agree it's kind of confusing right now. Nobody's going to be deploying docker on their laptop or anything!

**Pull request merged**
