### PR TITLE
Add cost estimate column

### PR DESCRIPTION
**Pull request by simonv3**
To give interested admin an idea of what expected costs might be.

### CODE REVIEW

**Comment by wxcafe** [comment]
I'm pretty sure you could figure that out by looking at the hosting provider link and the specs of the server/VPS? That's what I envisioned when I created the page at least, what do you think?

**Comment by simonv3** [comment]
@wxcafe There's also all sorts of costs that go into this that aren't necessarily to do with a specific provider link. For example @ashfurrow's post also considers email costs and those kind of things. 

At a glance this information would be really helpful to me if I were going to pursue setting up an instance. Cost is a big factor.

I wanted to track this information, thought it made sense to do so publicly and thought that this was the most sensible place to include it. I'm open for other suggestions though!

**Comment by wxcafe** [comment]
I mean, I host my own email, but sure. Please update the PR and I'll merge it

**Comment by simonv3** [comment]
Thanks!

**Pull request merged**
