### PR TITLE
"gcc-6" should just be "gcc"

### PR DESCRIPTION
**Pull request by staticsafe**
gcc-6 isn't a valid package name

### CODE REVIEW

**Comment by staticsafe** [comment]
to be more specific with that second commit, it was --system that broke su - as using --system gives the user the shell /bin/false.

"A home directory is created by the same rules as for normal users.  The new system user will have the shell /bin/false (unless overridden with the --shell option), and have logins disabled.  Skeletal configuration files are not copied."

**Comment by Gargron** [comment]
I personally just do `adduser --disabled-login mastodon`

**Comment by staticsafe** [comment]
--disabled-login also breaks su - mastodon immediately after in the guide as that means the user can't login without a password set.

**Comment by Gargron** [comment]
I just do `sudo su - mastodon` and it works (it takes *my* password, not mastodon's)

**Comment by staticsafe** [comment]
using sudo su - now instead

**Pull request merged**
