### PR TITLE
Resources needed: Add oc.todon.fr stats and more columns

### PR DESCRIPTION
**Pull request by ProgVal**

### CODE REVIEW

**Comment by Angristan** [comment]
90MB/s and  900MB/s ? It's not possible, and even in Mb/s Mastodon does not use that much bandwidth

**Comment by ProgVal** [comment]
Oh crap, it's KB/s, not MB/s

**Comment by ProgVal** [comment]
Actually, it's Kb/s -_-

**Comment by wxcafe** [comment]
kbps even

**Comment by Angristan** [comment]
Kb/s = Kbps ^^

**Comment by ProgVal** [comment]
cohérent *

**Comment by wxcafe** [comment]
è_è

**Pull request merged**
