### PR TITLE
Add PHP api wrapper

### PR DESCRIPTION
**Pull request by r-daneelolivaw**

### CODE REVIEW

**Comment by nightpool** [comment]
it would be confusing to have two projects named mastodon-api-php on the list—do you think it might be useful to rename yours to avoid confusion? 

let me know, I'm happy to accept the pull request either way.

**Comment by wxcafe** [comment]
@r-daneelolivaw up on this?

**Comment by r-daneelolivaw** [comment]
@nightpool @wxcafe sorry for this late reply, I'm not keen on changing the repo name because it describes simply what it does and has already references in a [Drupal module](https://www.drupal.org/project/mastodon) and Packagist but really agree on avoiding confusion, so I propose to highlight the difference between the 2 projects in the label by replacing

`[mastodon-api-php](https://github.com/r-daneelolivaw/mastodon-api-php)`

by 

`[Composer based PHP API wrapper](https://github.com/r-daneelolivaw/mastodon-api-php)`

**Comment by wxcafe** [comment]
sure yeah, go ahead.

**Pull request closed without merging**
