### PR TITLE
Adds IPv6 to my instance

### PR DESCRIPTION
**Pull request by ashfurrow**

### CODE REVIEW

**Comment by wxcafe** [comment]
Hey! I ran a RIPE-Atlas measurement for DNS resolution to mastodon.technology and it looks like you want to fix this 
screenshot from 2017-04-14 09-12-24
(these are all empty responses, you don't have an AAAA record)

**Comment by sakiti** [comment]
Where is here?

**Comment by ashfurrow** [comment]
Thanks, I'll get on that asap!!

**Comment by ashfurrow** [comment]
Should be fixed now, pending any DNS propagation delays.

**Comment by wxcafe** [comment]
I'll do a new test when I get access to The Onlines and merge this if it works

Clément 'wxcafé' Hertling

**Pull request merged**
