### PR TITLE
Renamed Ressources to Resources in filename and text

### PR DESCRIPTION
**Pull request by CoachEd**
I renamed the **Ressources-needed.md** file to **Resources-needed.md**. I made a similar change in the content too (1 occurrence). If I'm missing the joke or the intentional use of French, please deny this pull request. Thanks. - Ed

### CODE REVIEW

**Comment by nightpool** [comment]
haha came here to make this exact PR.

Maybe clean up your merge commits with `git rebase`?

**Comment by CoachEd** [comment]
Ok. I have done a "git rebase". Thanks for letting me know.

**Comment by nightpool** [comment]
Looks like you didn't push them, though

**Comment by CoachEd** [comment]
I'm sorry. I'm sort of new at this. I did `git rebase` locally and did a `git push`. So I thought the pull request would update automatically, right?

**Comment by CoachEd** [comment]
Gonna close and try this again, with cleaned up merge commits in my local repo.

**Comment by nightpool** [comment]
@CoachEd don't worry about it, I'll create a PR for the fix :P

**Comment by CoachEd** [comment]
Ok. Thanks!

**Pull request closed without merging**
