### PR TITLE
Add default CSP (take 2)

### PR DESCRIPTION
**Pull request by nolanlawson**
Follow up to https://github.com/tootsuite/documentation/pull/127, with the goal of addressing the concerns in https://github.com/tootsuite/documentation/pull/127#issuecomment-297661478.

This is what we're currently running on toot.cafe and doesn't seem to cause any issues. Scores an A- on Mozilla Observatory – AFAICT it's not possible to score A+ because removing `script-src 'unsafe-inline'` will result in a console error in Firefox.

I think it's important to at least have a default recommended CSP because a lot of instances seem to be rolling their own, which can cause compat issues, e.g. there was discussion [on Matrix](https://matrix.to/#/!VMUpuubSCTxMbZkuZa:cybre.space/$1493869579852685YXIjI:matrix.org) about mst3k federation being broken due to a bad CSP.

### CODE REVIEW

**Comment by fwenzel** [comment]
No seriously, don't allow unsafe inline scripts.

**Comment by fwenzel** [comment]
I'll close my PR in favor of this one.

**Comment by fwenzel** [comment]
I like the `media-src` and `img-src` on `https:`. I am sure there are possible security concerns here, but we're talking about user-uploaded media even locally, so.

This also helps with the ongoing work on deciding what media to reproduct locally as opposed to deep-link on the origin host.

**Comment by fwenzel** [comment]
Can you screenshot the alleged Firefox error for me? I cannot reproduce it.

**Comment by nolanlawson** [comment]
I can't reproduce the Firefox error anymore either, as of 1.3.3 anyway. Maybe it's fine just to do `script-src 'self'`.

**Comment by nolanlawson** [comment]
OK, the new version is live now on toot.cafe. I'm trying to reproduce the old Firefox console error but cannot, so this seems good to me.

**Comment by nolanlawson** [comment]
BTW I'm not 100% sold on `strict-origin-when-cross-origin`. Chrome doesn't seem to support it (just shows a console error), meaning that it's essentially like adding nothing. I'm going to remove it for now; it can be covered in another PR since it's technically unrelated to CSP anyway. /cc @ashfurrow

**Comment by nolanlawson** [comment]
FWIW according to [the MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), only Chrome and Firefox support the header at all, and only Firefox supports `strict-origin-when-cross-origin`, but Chrome does support `origin-when-cross-origin`.

**Comment by fwenzel** [comment]
Thanks! And no prob if you're not an expert on this, seems like both @nolanlawson and I have worked with CSPs for a while.

**Comment by fwenzel** [comment]
@nolanlawson agreed on the referrer policy. I do like origin-when-cross-origin, so long as that works with both Chrome and Firefox? Anyway, new PR time.

**Comment by Grayswandir** [comment]
Hello, sorry to reopen this conversation one year later, but maybe I miss something about the CSP:
- My instance is B for Mozilla because of the CSP, no CSP on my instance, so I searched for documentation.
- This ticket #204 seem to be the last one about this subject, the others tickets are closed.
- You seem to agree to have a default recommendation CSP, good for me :)
- git:mastodon/docs/running/production-guide: go to the git:documentation
- git:documentation/docs/running/production-guide: no mention of CSP config
- but I can find a commit: b98af5e96d9e87870190722eeca34a807abfc15c with CSP config, but I don't know when it's delete and why.
- V2.4.0: there is mention of troubleshooting with CSP config "(allow blob: as img-src and connect-src)".
Can someone help me to understand? 
What is the default CSP config recommended?
Thank you for your help

**Comment by Gargron** [comment]
We don't recommend using a CSP header because it needs to be carefully maintained, basically you need to understand well what you are doing to use it. The ones that get copypasted and recommended, contain stuff that breaks parts of Mastodon, and then we get complaints like "Why don't image uploads work", or "Why don't YouTube videos get embedded" etc etc. Use a CSP header at your own risk.

**Comment by Grayswandir** [comment]
Ok, I understand the point. Maybe it could be good to add a commentary in the documentation, to warn people about the CSP, like you said: "Use a CSP header at your own risk.". Or present differents (2-3) examples of CSP config, commented with '#', with full safe -ie without video/picture-, half-safe, no-safe?
ps: it's the right place for this discussion? Or another place? Via mastodon maybe? Mailing? to late for the discussion?

**Pull request merged**
