### PR TITLE
enabled TLSv1.3

### PR DESCRIPTION
**Pull request by ashleyhull-versent**

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Don't you need `boringssl` installed for that to work? Not sure if that'll work with `openssl` (and I'm pretty sure most users have `openssl` installed). Also nginx 1.15.3 should be used, and the number of users compiling the latest nginx themselves is pretty low.

IMHO it's a bit early to include it like that in the config. But you can add a comment saying that it is possible to add TLSv1.3 provided you have nginx > 1.15.3 + boringssl.

**Comment by ashleyhull-versent** [comment]
nginx supports TLSv1.3 on recent revisions of Ubuntu packages... but openssl doesn't so you'd need to compile boringssl (yes)... but having this enabled will "fail" until the package is updated, and then it will just work - no harm... plus we're being ubuntu centric.. other distros support TLSv1.3 (arch or example).

So this is future proofing

>mastodon@ip-10-0-0-140:~$ sudo cat /etc/nginx/nginx.conf | grep TLS
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE

>mastodon@ip-10-0-0-140:~$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

>mastodon@ip-10-0-0-140:~$ sudo nginx -v
nginx version: nginx/1.14.0 (Ubuntu)

**Comment by nightpool** [comment]
Ubuntu 16.04 LTS only contains Nginx version 1.9, so I think this would be an error on that version. With that in mind, I don't think we should add it to the default configuration.

**Comment by ashleyhull-versent** [comment]
agreed.

**Pull request closed without merging**
