### PR TITLE
fix halcyon url

### PR DESCRIPTION
**Pull request by jeroenpraat**

### CODE REVIEW

**Comment by nightpool** [comment]
The new URL is a completely different maintainer and forked codebase, it should go under a different name and the mastodon account links also need to be updated.

**Comment by jeroenpraat** [comment]
@nightpool This was the commit that changed it to the new repo from the same Github user: https://github.com/jeroenpraat/documentation/commit/89068a4583bb18e83a2ed880046a73bd8549f8c6#diff-0d2eab7eff07aaa481d463dd8a514b31

I don't see any old repo and maintainer. The reason I changed this url, is cause that site is offline. In the README there are other sites people can use.

**Comment by nightpool** [comment]
The github user "halcyon" has now belonged to two different people. It was taken over by a new maintainer around march.

**Comment by jeroenpraat** [comment]
OK, but which is the good one now?

**Pull request closed without merging**
